#ifndef _KISS_CONFIG_H
#define _KISS_CONFIG_H

#define KISS_ENABLE_SERIAL 1
#define KISS_ENABLE_SERIAL_TX 1
#define KISS_ENABLE_SERIAL_RX 1
#define KISS_SERIAL_TX_BUF_SIZE 0x100

#endif // _KISS_CONFIG_H
